### PR TITLE
Improvements to the 2.2 branch

### PR DESCRIPTION
**Pull request by rgabo**
Cascading! We're relying on this awesome project to bootstrap a local, but distributed test environment and I came across a few trivial improvements that we did in our fork and saw no harm in putting in a PR:
- Bump HBase to 0.94.15 as 0.94.13 is nowhere to be found (at least on the mirrors closest to us)
- Upgrade Vagrantfile to the V2 Configuration API and add `vm_box_url` so a simple `vagrant up` does the job even if the precise64 box is not available yet
- Share the tarballs across the VMs through a `tmp` directory instead of the project root and ignore, so that the git repository stays clean
- Clean unnecessary git ignores

More than happy to do the same when 2.5 is official/stable. We're also planning on adding Pig to the mix through a new module.

Thanks for the awesome work!

### CODE REVIEW

**Comment by fs111** [comment]
Hi,

thanks for the improvements, I added a few questions and remarks to the commits.

**Comment by rgabo** [comment]
@fs111 I should have fixed all the issues, let me know if there's anything else you think needs fixing. re: networking, it works like a charm, master.local and the others can be pinged, all web interfaces work so it resolves.

**Comment by fs111** [comment]
looks good. Thanks for the patches!

**Comment by rgabo** [comment]
happy to contribute!

**Pull request merged**
